### ISSUE TITLE
cargo build --release error

### ISSUE THREAD

**Issue by forliuyifei** [ogham/exa#821]
- git rev-parse --short HEAD  
  13b91cc
- rustc --version  
  rustc 1.41.1
- uname -a
Linux HP-735G5-Deepin 5.10.5-amd64-desktop+ #1 SMP Mon Jan 11 14:55:28 CST 2021 x86_64 GNU/Linux
- rustc --print cfg
debug_assertions
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix

the output of the build process.

```
$ cargo build --release
   Compiling exa v0.9.0 (/home/xxx/GIT/exa)
error[E0658]: use of unstable library feature 'matches_macro'
   --> src/fs/file.rs:473:9
    |
473 |         matches!(self, Self::Broken(_) | Self::Err(_))
    |         ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
  --> src/fs/fields.rs:60:9
   |
60 |         matches!(self, Self::File)
   |         ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> src/options/mod.rs:180:53
    |
180 |         let dir_action = DirAction::deduce(matches, matches!(view.mode, Mode::Details(_)))?;
    |                                                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `exa`.

To learn more, run the command again with --verbose.
```
---

**Comment by ariasuni** [comment]
According to [the section “Development” in the README](https://github.com/ogham/exa#development--------):
> exa is written in Rust. You will need rustc version 1.42.0 or higher. The recommended way to install Rust for development is from the official download page, using rustup.

Please report if exa fails to compile with Rust 1.42.0 or higher.

**Comment by ariasuni** [comment]
I have the same error as you with Rust 1.41.1 but it works with Rust 1.42.0.

**Comment by massimiliano-della-rovere** [comment]
rustc 1.61.0
ubuntu 22.04.01 LTS
cargo 1.61.0



cargo install exa

    Updating crates.io index
  Installing exa v0.10.1
   Compiling libc v0.2.139
   Compiling pkg-config v0.3.26
   Compiling tinyvec_macros v0.1.0
   Compiling unicode-width v0.1.10
   Compiling log v0.4.17
   Compiling cfg-if v1.0.0
   Compiling unicode-bidi v0.3.8
   Compiling percent-encoding v2.2.0
   Compiling bitflags v1.3.2
   Compiling byteorder v1.4.3
   Compiling ansi_term v0.12.1
   Compiling natord v1.0.9
   Compiling glob v0.3.0
   Compiling number_prefix v0.4.0
   Compiling lazy_static v1.4.0
   Compiling scoped_threadpool v0.1.9
   Compiling tinyvec v1.6.0
   Compiling pad v0.1.6
   Compiling term_grid v0.1.7
   Compiling form_urlencoded v1.1.0
   Compiling unicode-normalization v0.1.22
   Compiling jobserver v0.1.25
   Compiling locale v0.2.2
   Compiling num_cpus v1.15.0
   Compiling users v0.11.0
   Compiling term_size v0.3.2
   Compiling cc v1.0.78
   Compiling idna v0.3.0
   Compiling datetime v0.5.2
   Compiling url v2.3.1
   Compiling exa v0.10.1
   Compiling zoneinfo_compiled v0.5.1
   Compiling libz-sys v1.1.8
   Compiling libgit2-sys v0.12.26+1.3.0
   Compiling git2 v0.13.25
error: could not compile `exa`

Caused by:
  process didn't exit successfully: `rustc --crate-name exa --edition=2018 /home/mader/.cargo/registry/src/github.com-1ecc6299db9ec823/exa-0.10.1/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto --cfg 'feature="default"' --cfg 'feature="git"' --cfg 'feature="git2"' -C metadata=ce71e745b696ab4d -C extra-filename=-ce71e745b696ab4d --out-dir /tmp/cargo-installfpurft/release/deps -L dependency=/tmp/cargo-installfpurft/release/deps --extern ansi_term=/tmp/cargo-installfpurft/release/deps/libansi_term-453b9d42873e2c24.rlib --extern datetime=/tmp/cargo-installfpurft/release/deps/libdatetime-df3965db44c6e2bc.rlib --extern git2=/tmp/cargo-installfpurft/release/deps/libgit2-274a2991d56034d3.rlib --extern glob=/tmp/cargo-installfpurft/release/deps/libglob-aa28c5b0b0e3a445.rlib --extern lazy_static=/tmp/cargo-installfpurft/release/deps/liblazy_static-14caf7f48ee3d138.rlib --extern libc=/tmp/cargo-installfpurft/release/deps/liblibc-eba45ade47aafe12.rlib --extern locale=/tmp/cargo-installfpurft/release/deps/liblocale-5990dff9b25fba34.rlib --extern log=/tmp/cargo-installfpurft/release/deps/liblog-9d0e063a7d97f0b3.rlib --extern natord=/tmp/cargo-installfpurft/release/deps/libnatord-d4ca9530037b4b8a.rlib --extern num_cpus=/tmp/cargo-installfpurft/release/deps/libnum_cpus-1835ab18780f5252.rlib --extern number_prefix=/tmp/cargo-installfpurft/release/deps/libnumber_prefix-9bae3fc9e327fed9.rlib --extern scoped_threadpool=/tmp/cargo-installfpurft/release/deps/libscoped_threadpool-bd9254a24cf9b7eb.rlib --extern term_grid=/tmp/cargo-installfpurft/release/deps/libterm_grid-94904aa73ea498c3.rlib --extern term_size=/tmp/cargo-installfpurft/release/deps/libterm_size-da6b351c1ea972fb.rlib --extern unicode_width=/tmp/cargo-installfpurft/release/deps/libunicode_width-55f731749c273594.rlib --extern users=/tmp/cargo-installfpurft/release/deps/libusers-f98383eea14a4050.rlib --extern zoneinfo_compiled=/tmp/cargo-installfpurft/release/deps/libzoneinfo_compiled-5ae2d9800aaaee20.rlib --cap-lints allow -L native=/tmp/cargo-installfpurft/release/build/libgit2-sys-1153c733a68bb401/out/build` (signal: 8, SIGFPE: erroneous arithmetic operation)
error: failed to compile `exa v0.10.1`, intermediate artifacts can be found at `/tmp/cargo-installfpurft`
