### ISSUE TITLE
Compilation failed on aarch64

### ISSUE THREAD

**Issue by neepoo** [ogham/exa#887]
- The exact exa commit you are building: 

> a6754f3

- The version of rustc you are compiling it with

>  rustc 1.52.1 (9bc8c42bb 2021-05-09)

- Your operating system and hardware platform

> Linux arm-ubuntu 5.4.0-1045-oracle #49-Ubuntu SMP Mon May 3 05:27:18 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

- The Rust build target

```debug_assertions
target_arch="aarch64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
```

I run `cargo check` but I get the following
```
❯ cargo check
    Checking exa v0.10.1 (/home/xxx/code/exa)
error[E0308]: mismatched types
   --> src/fs/feature/xattr.rs:265:21
    |
265 |                     buf.as_mut_ptr().cast::<i8>(),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

error[E0308]: mismatched types
   --> src/fs/feature/xattr.rs:280:21
    |
280 |                     buf.as_ptr().cast::<i8>(),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `exa`

To learn more, run the command again with --verbose.
```

Then I modified according to the error report， change `i8` to `u8`,it gets ok.

**Comment by alexmaco** [comment]
I'm also seeing this exact error on armv7.

uname -a:
```
Linux tinkerboard 4.4.132+ #8 SMP Thu Aug 13 08:51:08 UTC 2020 armv7l GNU/Linux
```

Target:
```
debug_assertions
target_arch="arm"
target_endian="little"
target_env="gnu"
target_family="unix"
target_os="linux"
target_pointer_width="32"
target_vendor="unknown"
unix
```

**Comment by eggbean** [comment]
10.1 compiles through cargo fine on my RasPi with armv7, but the latest version that I can compile on aarch64 is 0.9.

**Comment by ariasuni** [comment]
Fixed by 8ad8b33!
